# Here so that we can comment out the second instance. Looks terrible but works.
networks:
  airAuth1:
    driver: bridge
  airAuth2:
    driver: bridge
  airAuth3:
    driver: bridge
  airAuthServers:
    driver: bridge

services:
  postgres1:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=airAuth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./volumes/postgres1:/var/lib/postgresql/data
    restart: 'always'
    networks:
      - airAuth1

  airAuth1:
    image: airauthserverdev:latest
    ports:
      - 8080:8080
      - 5555:5555
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres1:5432/airAuth?schema=public
      - CIPHER_IV=#hzCY@5&S#JqvDgS1
    volumes:
      - ./dist:/app/dist
      - ./config/pems:/app/config/pems
      - ./config/server1.config.json:/app/config/config.json
    networks:
      - airAuth1
      - airAuthServers
    depends_on:
      - postgres1

  postgres2:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=airAuth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DUMMY_DATA=true
    volumes:
      - ./volumes/postgres2:/var/lib/postgresql/data
    restart: 'always'
    networks:
      - airAuth2

  airAuth2:
    image: airauthserverdev:latest
    ports:
      - 8081:8080
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres2:5432/airAuth?schema=public
      - CIPHER_IV=#hzCY@5&S#JqvDgS1
    volumes:
      - ./dist:/app/dist
      - ./config/pems:/app/config/pems
      - ./config/server2.config.json:/app/config/config.json
    networks:
      - airAuth2
      - airAuthServers
    depends_on:
      - postgres2

  # postgres3:
  #   image: postgres:14-alpine
  #   environment:
  #     - POSTGRES_DB=airAuth
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - ./volumes/postgres3:/var/lib/postgresql/data
  #   restart: 'always'
  #   networks:
  #     - airAuth3

  # airAuth3:
  #   image: airauthserverdev:latest
  #   ports:
  #     - 8082:8080
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres3:5432/airAuth?schema=public
  #     - CIPHER_IV=#hzCY@5&S#JqvDgS1
  #   volumes:
  #     - ./dist:/app/dist
  #     - ./config/pems:/app/config/pems
  #     - ./config/server3.config.json:/app/config/config.json
  #   networks:
  #     - airAuth3
  #     - airAuthServers
  #   depends_on:
  #     - postgres3
