services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=airAuth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: 'always'
